apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k2marketing-api
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
spec:
  ingressClassName: nginx
  rules:
    - host: k2marketing.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: k2marketing-api
                port:
                  name: http
  tls:
    - hosts:
        - k2marketing.example.com
      secretName: k2marketing-tls
