apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: k2marketing
commonLabels:
  app.kubernetes.io/part-of: k2marketing
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
