apiVersion: v1
kind: Service
metadata:
  name: k2marketing-api
  labels:
    app: k2marketing-api
spec:
  selector:
    app: k2marketing-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
