apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k2marketing
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kristoffershoar/k2MarketingAi.git
    targetRevision: main
    path: deploy/k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: k2marketing
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 5
