apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: k2marketing
resources:
  - ../../base
images:
  - name: ghcr.io/iranigeeks/k2marketingai
    newName: ghcr.io/iranigeeks/k2marketingai
    newTag: v0.1.0
patches:
  - target:
      kind: Deployment
      name: k2marketing-api
    patch: |
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: Ingress
      name: k2marketing-api
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: prod.k2marketing.example.com
      - op: replace
        path: /spec/tls/0/hosts/0
        value: prod.k2marketing.example.com
      - op: replace
        path: /spec/tls/0/secretName
        value: k2marketing-tls
